apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pets-dog
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "dog-lover"
spec:
  rules:
  - host: canary.gp.kaluzny.io
    http:
      paths:
      - backend:
          serviceName: pets-dog
          servicePort: 8080
