apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-v1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - "echo-tls.gp.kaluzny.io"
    secretName: gp-kaluzny-io
  rules:
  - host: echo-tls.gp.kaluzny.io
    http:
      paths:
      - backend:
          serviceName: echo-v2
          servicePort: 80
        path: /
      - backend:
          serviceName: echo-v1
          servicePort: 80
        path: /api
---
apiVersion: v1
kind: Service
metadata:
  name: echo-v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: echo-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v1
spec:
  selector:
    matchLabels:
      app: echo-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-v1
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.4
          name: echo
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echo-v2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: echo-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v2
spec:
  selector:
    matchLabels:
      app: echo-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-v2
    spec:
      containers:
        - image: brndnmtthws/nginx-echo-headers
          name: echo
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
